common: &common
  adapter: postgresql
  username: postgres
  password:  # from psql setup, see Postgresql

development:
  <<: *common
  database: todo_development

test:
  <<: *common
  database: todo_test

production:
  <<: *common
  database: todo_production
